src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuteurRepository::class)]
class Auteur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateDeNaissance = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $biographie = null;

    #[ORM\OneToMany(mappedBy: 'auteur', targetEntity: Article::class)]
    private Collection $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->dateDeNaissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $dateDeNaissance): self
    {
        $this->dateDeNaissance = $dateDeNaissance;

        return $this;
    }

    public function getBiographie(): ?string
    {
        return $this->biographie;
    }

    public function setBiographie(string $biographie): self
    {
        $this->biographie = $biographie;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setAuteur($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getAuteur() === $this) {
                $article->setAuteur(null);
            }
        }

        return $this;
    }

    public function getFullName()
    {
        return $this->nom . " " . $this->prenom;
    }
}

src/Form/AuteurType.php
<?php

namespace App\Form;

use App\Entity\Auteur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class AuteurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('dateDeNaissance', BirthdayType::class);
           $builder->add('biographie')
                   ->add('Envoyer', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Auteur::class,
        ]);
    }
}

src/Controller/AuteurController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Auteur;
use App\Entity\Article;
use App\Form\AuteurType;
use App\Form\ArticleType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AuteurController extends AbstractController
{
    #[Route('/auteurs', name: 'app_auteurs')]
    public function auteurs(ManagerRegistry $doctrine): Response
    {
        // on récupère les articles
        $auteurs = $doctrine->getRepository(Auteur::class)->findBy([], ["id" => "DESC"]);

        // on vérifie si on a bien récupérer les articles
        return $this->render('auteur/auteurs.html.twig', [
            'auteurs' => $auteurs
        ]);
    }


    #[Route('/auteur_{id<\d+>}', name: 'app_auteur')]
    public function unAuteur(ManagerRegistry $doctrine, $id)
    {
        // on récupère l'article dont l'id est celui dans l'URL
        $auteur = $doctrine->getRepository(Auteur::class)->find($id);

        // on vérifie si je récupère bien un article
        // dd($unArticle);

        return $this->render('auteur/auteur.html.twig', [
            'auteur' => $auteur,
            'id' => $id,
        ]);
    }

    #[Route('/auteur_ajout', name: 'app_auteur_ajout')]
    public function ajout(Request $request, ManagerRegistry $doctrine)
    {
        // on crée un objet Article
        $auteur = new Auteur();

        // on lie ArticleType avec l'objet créé
        $form = $this->createForm(AuteurType::class, $auteur);

        $form->handleRequest($request);

        // vérifier qu'un formulaire est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {
            // on récupère le manager de doctrine
            $manager = $doctrine->getManager();

            $manager->persist($auteur);

            $manager->flush();

            return $this->redirectToRoute('app_auteurs');
        }

        return $this->render('auteur/formAuteur.html.twig', [
            'formAuteur' => $form->createView()
        ]);
    }

    #[Route('/auteur_editer_{id<\d+>}', name: 'app_auteur_editer')]
    public function edit(Request $request, ManagerRegistry $doctrine, $id)
    {
        $auteur = $doctrine->getRepository(Auteur::class)->find($id);

        $form = $this->createForm(AuteurType::class, $auteur);

        $form->handleRequest($request);

        // vérifier qu'un formulaire est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {
            // on récupère le manager de doctrine
            $manager = $doctrine->getManager();

            $manager->persist($auteur);

            $manager->flush();

            return $this->redirectToRoute('app_auteurs');
        }

        return $this->render('auteur/formAuteur.html.twig', [
            'formAuteur' => $form->createView()
        ]);
    }

    #[Route('/auteur_delete_{id<\d+>}', name: 'app_auteur_delete')]
    public function delete(ManagerRegistry $doctrine, $id)
    {
        $auteur = $doctrine->getRepository(Auteur::class)->find($id);

        $manager = $doctrine->getManager();

        $manager->remove($auteur, 1);

        return $this->redirectToRoute('app_auteurs');
    }
}

templates/auteur/auteur.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Auteur{% endblock %}

{% block content %}
<div class="justify-content-center text-center mt-5">
	<img src="" alt="">
	<h2>
		{{ auteur.fullName }}
	</h2>
	<h4>
		écrit par
	</h4>
	<h6 class="text-muted">créé le
		{{ auteur.dateDeNaissance|date("d/m/Y \à H\\hi") }}</h6>
	<h6 class="text-muted">
		date de modification
	</h6>
	<div class="row justify-content-center">
		<div class="col-offset-2 col-8">
			<p>
				{{ auteur.biographie}}
			</p>
		</div>
	</div>
</div>

{% endblock %}

templates/auteur/auteurs.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Tous les auteurs
{% endblock %}

{% block content %}
<table class="mt-5 table table-striped border" style="border-collapse: separate; border-radius: 20px">
	<thead>
		<tr>
			<th scope="col">Nom</th>
			<th scope="col">Prénom</th>
			<th scope="col">Date de naissance</th>
			<th scope="col">Biographie</th>
            <th scope="col">Action</th>
		</tr>
	</thead>
	<tbody>
    {% for auteurs in auteurs %}
		<tr>
			<td>{{auteurs.nom}}</td>
            <td>{{auteurs.prenom}}</td>
            <td>{{auteurs.dateDeNaissance|date('d/m/Y')}}</td>
            <td>{{auteurs.biographie|slice(0, 20)}}...</td>
        
            <td>
                <a class="btn btn-success" href="{{ path('app_auteur', { id : auteurs.id }) }}">Voir</a>
                <a class="btn btn-warning" href=" {{ path('app_auteur_editer', { id : auteurs.id } ) }}">Editer</a>
                <a class="btn btn-danger attention" href="{{ path('app_auteur_delete', { id : auteurs.id }) }}">Supprimer</a>
            </td>
		</tr>
    {% endfor %}
	</tbody>
</table>

<script>

window.alert=function(msg){
    addEventListener('click', (event) => {
        $btn = document.querySelector('a');
        if($btn){
            alert("attention vous êtes sur le point de supprimer un auteur")
        }
    });
}

window.alert = function(message) {
    if(message == 'Adblock detected, please consider disabling it') {
        console.log(message);
    } else {
        confirm(message);
    }
}

</script>

{% endblock %}

templates/auteur/formAuteur.html.twig
{% extends "layout.html.twig" %}

{% block title %}
	formulaire Article
{% endblock title %}

{% block content %}
	<h1>Ajout d'un auteur</h1>
	{{ form(formAuteur) }}
{% endblock content %}